logging:
  level:
    org:
      springframework:
        boot: INFO
        security: DEBUG
      apache:
        tiles: INFO
        web: DEBUG
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql: trace
    root: INFO
    com:
      samsung:
        security: DEBUG

server:
  servlet:
    contextPath: /
    encoding:
      enabled: 'true'
      force: 'true'
      charset: UTF-8
  port: '8080'

#mysal JPA
spring:
  jpa:
    hibernate:
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
      ddl-auto: update
      use-new-id-generator-mappings: 'true'
    properties:
      hibernate:
        format_sql: 'true'
        show_sql: 'true'
    database: mysql
    show-sql: 'true'

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      password: ssafy
      username: drdoc
    url: jdbc:mysql://localhost:3306/drdoc?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true

  devtools:
    livereload:
      enabled: 'true'

  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

  jackson:
    serialization:
      fail-on-empty-beans: false

build:
  date: '@build.date@'
springfox:
  documentation:
    swagger:
      use-model-v3: 'false'

#JWT
jwt:
  header: Authorization
  #HS512 알고리즘을 사용할 것이기 때문에 512bit, 즉 64byte 이상의 secret key를 사용해야 한다.
  #echo 'silvernine-tech-spring-boot-jwt-tutorial-secret-silvernine-tech-spring-boot-jwt-tutorial-secret'|base64
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  token-validity-in-seconds: 86400  #하루
